### PR TITLE
threadUpdate: Combine thread and oldThread types

### LINKED ISSUE #20: Second parameter is required for the threadUpdate event
image

image

### PR DESCRIPTION
**Pull request by Christian-Toney**
Fixes #20

### CODE REVIEW

**Comment by DonovanDMC** [comment]
The typings are as is for a reason

**Comment by Christian-Toney** [comment]
@DonovanDMC What's the reason? TypeScript doesn't require all function parameters to be used

**Comment by DonovanDMC** [comment]
Having everything typed separately allows narrowing one to narrow the other

**Comment by Christian-Toney** [comment]
That makes sense. Thanks!

**Pull request closed without merging**
