### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by face-hh** [comment]
Plz fix library literally unusable with these

**Comment by DonovanDMC** [comment]
I'm putting it out there right now that I'm not accepting pull requests for fixing a few words

**Comment by doomestee** [comment]
ngl some of the typos are blatantly hilarious

**Comment by DonovanDMC** [comment]
I'm going to bon you

**Comment by ghost** [comment]
damn, now i have to continue typing OAuth#getRoleConnectionMeta**t**data, so sad.

**Pull request closed without merging**
